### Numpy Random Notebook
- A jupyter notebook explaining the concepts behind and the use of the numpy package, including plots of the various distributions.
- Numpy.random package is a sub package of the numpy package in Python and is responsible for generating random numbers in lot's of different ways.

#### What is NumPy?
- NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
    
#### Numpy Random package can be categorised into:
- __Simple random data__, which includes functions for everyday use, such as __*rand(d0, d1, …, dn)*__ to generate random values in a given shape.
- __Permutations__, which includes function such as __*shuffle(x)*__ to modify a sequence in-place by shuffling its contents.
- __Distributions__, which are realated to different probability distributions, example of a function would be __*exponential([scale, size])*__ which would draw samples from an exponential distribution.
- __Random generator__ which includes function such as __*seed([seed])*__ to seed the generator.
***

In [2]:
# Import numpy package as np to allow access to numpy.random package
import numpy as np

#### Functions to be investigated:
- Simple random data
    - [rand(d0, d1, …, dn)](#rand)
    - [randint(low, high=None, size=None, dtype='l')](#randint)
    - [random([size])](#random)
    - [choice(a[, size, replace, p])](#choice)
    - [ranf([size])](#ranf)
- Permutations
    - [shuffle(x)](#shuffle)
- Distributions
    - [exponential([scale, size])](#exponential)
    - [normal([loc, scale, size])](#normal)
    - [geometric(p[, size])](#geometric)
    - [uniform([low, high, size])](#uniform)
- Random generator
    - [seed([seed])](#seed)

***
<a id="rand"></a>
### numpy.random.rand
- Random values in a given shape.
- Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1].

- **Parameters:** 
    - d0, d1, …, dn : int, optional
        - The dimensions of the returned array, should all be positive. If no argument is given a single Python float is returned.
- **Returns:** 
    - out : ndarray, shape (d0, d1, ..., dn)
        - Random values.

In [52]:
# Without arguments function will return random single float number (from 0 to 1)
print("No arguments: ")
np.random.rand()

No arguments: 


0.05832934297976866

In [53]:
# With one argument it will return number of random float numbers (from 0 to 1) specified
print("With one argument '3': ")
np.random.rand(3)

With one argument '3': 


array([0.72441471, 0.11468285, 0.81804689])

In [54]:
# With two arguments it will return matrices specified of random float numbers (from 0 to 1)
print("With two arguments '2,2': ")
np.random.rand(2,2)

With two arguments '2,2': 


array([[0.64472261, 0.81581367],
       [0.6130365 , 0.91321576]])

In [55]:
# With three arguments it will return matrices specified of random float numbers (from 0 to 1)
# By continuing to add more arguments, it will simply add more dimensions to the matrices
print("With three arguments '2,2,2': ")
np.random.rand(2,2,2)

With three arguments '2,2,2': 


array([[[0.72726816, 0.74400231],
        [0.73455863, 0.62051414]],

       [[0.958561  , 0.70507497],
        [0.33158693, 0.37502753]]])

***
<a id="randint"></a>
### numpy.random.randint
- Return random integers from low (inclusive) to high (exclusive).
- Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

- **Parameters:**
    - low : int
        - Lowest (signed) integer to be drawn from the distribution (unless high=None, in which case this parameter is one above the highest such integer).
    - high : int, optional
        - If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None).
    - size : int or tuple of ints, optional
        - Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
    - dtype : dtype, optional
        - Desired dtype of the result. All dtypes are determined by their name, i.e., ‘int64’, ‘int’, etc, so byteorder is not available and a specific precision may have different C types depending on the platform. The default value is ‘np.int’.
        - New in version 1.11.0.

- **Returns:**
    - out : int or ndarray of ints
        - size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

In [52]:
# Must take at least one argument
# With one argument it generates random int up to 4, inclusive
print("One argument '5' generates random int from 0 to 4: ")
np.random.randint(5)

One argument '5' generates random int from 0 to 4: 


3

In [53]:
# With two arguments it generates random int between 5 and 14, inclusive
print("Arguments '5' & '10' generates random int between 5 and 9, inclusive: ")
np.random.randint(5, 10)

Arguments '5' & '10' generates random int between 5 and 9, inclusive: 


6

In [54]:
# With three arguments it generates random ints between 5 and 9, inclusive
# where third number determines size of randomly generated ints
print("Arguments '5, 10, 5' generates five random ints between 5 and 9, inclusive:: ")
np.random.randint(5, 10, 5)

Arguments '5, 10, 5' generates five random ints between 5 and 9, inclusive:: 


array([8, 7, 5, 6, 5])

In [56]:
# Generate a 2 x 4 array of ints between 5 and 14, inclusive
print("Arguments '5, size=(2, 4)' a 2 x 4 array of ints between 5 and 14, inclusive: ")
np.random.randint(5, 15, size=(2, 4))

Arguments '5, size=(2, 4)' a 2 x 4 array of ints between 5 and 14, inclusive: 


array([[ 8, 12, 12,  9],
       [ 5,  7, 14, 10]])

***
<a id="random"></a>
### numpy.random.random

***
<a id="choice"></a>
### numpy.random.choice

***
<a id="ranf"></a>
### numpy.random.ranf

***
<a id="shuffle"></a>
### numpy.random.shuffle

***
<a id="exponential"></a>
### numpy.random.exponential

***
<a id="normal"></a>
### numpy.random.normal

***
<a id="geometric"></a>
### numpy.random.geometric

***
<a id="uniform"></a>
### numpy.random.uniform

***
<a id="seed"></a>
### numpy.random.seed

***
###### References: 
- __[Random sampling (numpy.random)](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html )__
- __[What is NumPy?](https://docs.scipy.org/doc/numpy-1.13.0/user/whatisnumpy.html )__
- __[numpy.random.rand](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html#numpy.random.rand )__
- __[numpy.random.randint](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html)__
- __[numpy.random.random](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.random.html#numpy.random.random)__
- __[numpy.random.choice](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.choice.html#numpy.random.choice)__
- __[numpy.random.ranf](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.ranf.html#numpy.random.ranf)__
- __[numpy.random.shuffle](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.shuffle.html#numpy.random.shuffle)__
- __[numpy.random.exponential](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.exponential.html#numpy.random.exponential)__
- __[numpy.random.normal](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.normal.html#numpy.random.normal)__
- __[numpy.random.geometric](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.geometric.html#numpy.random.geometric)__
- __[numpy.random.uniform](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.uniform.html#numpy.random.uniform)__
- __[numpy.random.seed](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.seed.html#numpy.random.seed)__